urls.py
from django.urls import path
from . import views
#画像アップロードのために追加
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('upimg/', views.uploadimg, name="upimg"),
    path('imgview/', views.loginuser_imglist, name="imgview"),
    path('imgselect/<int:id>', views.imgselect, name="imgselect"),
]


#画像アップロードのために追加
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Upimage(models.Model):
    # on_deleteが必須 DO_NOTHINGは主レコードが削除されても何もしない
    owner = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    img = models.ImageField(upload_to='upimg/', blank=True)

forms.py
from django import forms
from .models import Upimage
#画像アップロードフォーム
class UpimageForm(forms.ModelForm):
    class Meta:
        model = Upimage
        fields = ('img', )

views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .forms import UpimageForm
from .models import Upimage

# Create your views here.
@login_required(login_url='login')
def uploadimg(request):
    loginuser = request.user
    if request.method == "POST":
        upimg = Upimage(owner=loginuser)
        upimgform = UpimageForm(request.POST, request.FILES, instance=upimg)
        upimgform.save()
        # img = Upimage(owner=loginuser, img=request.POST['img'])
        # img.save()
        params={
            'title':'Upload Completion',
            'head':'画像はアップロードされました!!',
        }
        #レンダリングするhtml用意
        #バリデーションも
        return render(request, 'imgadmin/standard.html', params)
    else:
        params={
            'title':'Upload Image',
            'head':'アップロードしたい画像を選択しましょう',
            'form':UpimageForm(),
        }
        #レンダリングするhtml用意
        return render(request, 'imgadmin/upimg.html', params)

#ログイン中ユーザのアップロード画像を一覧表示
@login_required(login_url='login')
def loginuser_imglist(request):
    loginuser = request.user
    params = {
        'title':'Image List View',
        'head':str(loginuser.username)+'さんがアップロードしている画像の一覧です。選択して使いたい機能を選びましょう',
        'loginuser':loginuser,
    }
    return render(request, 'imgadmin/imglist.html', params)


#パラメータとして送られてきたupimgのidを検索して画像を返す
@login_required(login_url='login')
def imgselect(request, id):
    slctupimg = Upimage.objects.filter(id=id)[0]
    loginuser=request.user
    if loginuser==Upimage.objects.filter(id=id)[0].owner:
        #画像所有者とログインユーザが同一の場合
        head='表示の画像に対して、どの機能を使いますか？'
    else:
        #画像所有者とログインユーザが異なる場合
        head='画像所有者はあなたではありません！'
        slctupimg=None
    params={
        'title':'Select function',
        'slctupimg':slctupimg,
        'head':head,
    }
    #selectimgを表示させながら、使いたい機能を選択できるhtmlをつくる
    return render(request, 'imgadmin/selectfunc.html', params)

templates/imgadmin/imglist.html
<!-- {% load static %} -->
<!DOCTYPE html>
<html lang=""ja>
    <head>
        <title>{{title}}</title>
        <!-- <link rel="stylesheet" type="text/css" href="{% static 'useradmin/css/standard.css' %}"/> -->
    </head>
    <body>
        <h1>{{head}}</h1>
        {% for upimg in loginuser.upimage_set.all %}
        <a href="{% url 'imgselect' upimg.id %}"><img src="{{upimg.img.url}}" width="30%" height="30%"/></a>
        {% endfor %}
        <p><a href="{% url 'top' %}">TOPへ</a></p>
    </body>
</html>

templates/imgadmin/selectfunc.html
<!-- {% load static %} -->
<!DOCTYPE html>
<html lang=""ja>
    <head>
        <title>{{title}}</title>
        <!-- <link rel="stylesheet" type="text/css" href="{% static 'useradmin/css/standard.css' %}"/> -->
    </head>
    <body>
        <h1>{{head}}</h1>
        <img src="{{slctupimg.img.url}}" width="30%" height="30%"/>
        <p><a href="{% url 'top' %}">TOPへ</a></p>
        <p><a href="{% url 'esrcfexe' slctupimg.id %}">ESRGAN（超解像）: 適切なモデルがあれば画像の解像度を自然にあげることができます。ただし色調の変化が起こり得ます。</a></p>
    </body>
</html>

templates/imgadmin/standard.html
<!-- {% load static %} -->
<!DOCTYPE html>
<html lang=""ja>
    <head>
        <title>{{title}}</title>
        <!-- <link rel="stylesheet" type="text/css" href="{% static 'useradmin/css/standard.css' %}"/> -->
    </head>
    <body>
        <h1>{{head}}</h1>
        <p><a href="{% url 'imgview' %}">アップロード済みの画像一覧</a></p>
    </body>
</html>

templates/imgadmin/upimg.html
<!-- {% load static %} -->
<!DOCTYPE html>
<html lang=""ja>
    <head>
        <title>{{title}}</title>
        <!-- <link rel="stylesheet" type="text/css" href="{% static 'useradmin/css/standard.css' %}"/> -->
    </head>
    <body>
        <h1>{{head}}</h1>
        <form method="post" action="{% url 'upimg' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="upload">
        </form>
    </body>
</html>